time="2019-08-27T09:58:00Z" level=error msg="\nYou haven't specified the sendAnonymousUsage option, it will be enabled by default.\n"
time="2019-08-27T09:58:09Z" level=error msg="Unable to obtain ACME certificate for domains \"test.local.com,test2.local.com\": unable to generate a certificate for the domains [test.local.com test2.local.com]: acme: Error -> One or more domains had a problem:\n[test.local.com] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for test.local.com, url: \n[test2.local.com] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for test2.local.com, url: \n" providerName=vcrobottlschallenge.acme routerName=test_local_com rule="Host(`test.local.com`, `test2.local.com`)"
time="2019-08-27T10:02:01Z" level=error msg="Unable to obtain ACME certificate for domains \"test.local.com,test2.local.com\": unable to generate a certificate for the domains [test.local.com test2.local.com]: acme: Error -> One or more domains had a problem:\n[test.local.com] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for test.local.com, url: \n[test2.local.com] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for test2.local.com, url: \n" routerName=test_local_com rule="Host(`test.local.com`, `test2.local.com`)" providerName=vcrobottlschallenge.acme
time="2019-08-27T10:03:58Z" level=error msg="Unable to obtain ACME certificate for domains \"test.local.com,test2.local.com\": unable to generate a certificate for the domains [test.local.com test2.local.com]: acme: Error -> One or more domains had a problem:\n[test.local.com] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for test.local.com, url: \n[test2.local.com] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for test2.local.com, url: \n" rule="Host(`test.local.com`, `test2.local.com`)" providerName=vcrobottlschallenge.acme routerName=test_local_com
time="2019-08-27T10:07:14Z" level=error msg="Unable to obtain ACME certificate for domains \"test.local.com,test2.local.com\": unable to generate a certificate for the domains [test.local.com test2.local.com]: acme: Error -> One or more domains had a problem:\n[test.local.com] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for test.local.com, url: \n[test2.local.com] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for test2.local.com, url: \n" providerName=vcrobottlschallenge.acme rule="Host(`test.local.com`, `test2.local.com`)" routerName=test_local_com
time="2019-08-27T10:32:17Z" level=error msg="accept tcp [::]:8080: use of closed network connection"
time="2019-08-27T10:32:17Z" level=error msg="accept tcp [::]:80: use of closed network connection"
time="2019-08-27T10:32:17Z" level=error msg="accept tcp [::]:443: use of closed network connection"
time="2019-08-27T10:33:31Z" level=error msg="\nYou haven't specified the sendAnonymousUsage option, it will be enabled by default.\n"
time="2019-08-27T10:33:35Z" level=error msg="Unable to obtain ACME certificate for domains \"test.local.com,test2.local.com\": unable to generate a certificate for the domains [test.local.com test2.local.com]: acme: Error -> One or more domains had a problem:\n[test.local.com] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for test.local.com, url: \n[test2.local.com] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for test2.local.com, url: \n" providerName=acme.vcrobottlschallenge routerName=test_local_com rule="Host(`test.local.com`, `test2.local.com`)"
time="2019-08-27T10:34:46Z" level=error msg="accept tcp [::]:8080: use of closed network connection"
time="2019-08-27T10:34:46Z" level=error msg="accept tcp [::]:80: use of closed network connection"
time="2019-08-27T10:34:46Z" level=error msg="accept tcp [::]:443: use of closed network connection"
time="2019-08-27T10:35:29Z" level=error msg="\nYou haven't specified the sendAnonymousUsage option, it will be enabled by default.\n"
time="2019-08-27T10:35:30Z" level=error msg="Unable to obtain ACME certificate for domains \"test.local.com,test2.local.com\": unable to generate a certificate for the domains [test.local.com test2.local.com]: acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rateLimited :: Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/, url: " providerName=vcrobottlschallenge.acme routerName=test_local_com rule="Host(`test.local.com`, `test2.local.com`)"
time="2019-08-27T10:36:52Z" level=error msg="accept tcp [::]:443: use of closed network connection"
time="2019-08-27T10:36:52Z" level=error msg="accept tcp [::]:8080: use of closed network connection"
time="2019-08-27T10:36:52Z" level=error msg="accept tcp [::]:80: use of closed network connection"
time="2019-08-27T10:37:12Z" level=error msg="\nYou haven't specified the sendAnonymousUsage option, it will be enabled by default.\n"
time="2019-08-27T10:37:15Z" level=error msg="Unable to obtain ACME certificate for domains \"test.local.com,test2.local.com\": unable to generate a certificate for the domains [test.local.com test2.local.com]: acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rateLimited :: Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/, url: " providerName=vcrobottlschallenge.acme routerName=test_local_com rule="Host(`test.local.com`, `test2.local.com`)"
time="2019-08-27T10:46:57Z" level=error msg="Unable to obtain ACME certificate for domains \"test.local.com,test2.local.com\": unable to generate a certificate for the domains [test.local.com test2.local.com]: acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rateLimited :: Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/, url: " routerName=test_local_com rule="Host(`test.local.com`, `test2.local.com`)" providerName=vcrobottlschallenge.acme
time="2019-08-27T10:47:48Z" level=error msg="Unable to obtain ACME certificate for domains \"test.local.com,test2.local.com\": unable to generate a certificate for the domains [test.local.com test2.local.com]: acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rateLimited :: Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/, url: " providerName=vcrobottlschallenge.acme routerName=test_local_com rule="Host(`test.local.com`, `test2.local.com`)"
time="2019-08-27T10:52:14Z" level=error msg="Unable to obtain ACME certificate for domains \"test.local.com,test2.local.com\": unable to generate a certificate for the domains [test.local.com test2.local.com]: acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rateLimited :: Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/, url: " rule="Host(`test.local.com`, `test2.local.com`)" providerName=vcrobottlschallenge.acme routerName=test_local_com
time="2019-08-27T11:02:23Z" level=error msg="Unable to obtain ACME certificate for domains \"test.local.com,test2.local.com\": unable to generate a certificate for the domains [test.local.com test2.local.com]: acme: Error -> One or more domains had a problem:\n[test.local.com] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for test.local.com, url: \n[test2.local.com] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for test2.local.com, url: \n" rule="Host(`test.local.com`, `test2.local.com`)" providerName=vcrobottlschallenge.acme routerName=test_local_com
time="2019-08-27T11:02:38Z" level=error msg="Unable to obtain ACME certificate for domains \"test.local.com,test2.local.com\": unable to generate a certificate for the domains [test.local.com test2.local.com]: acme: Error -> One or more domains had a problem:\n[test.local.com] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for test.local.com, url: \n[test2.local.com] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for test2.local.com, url: \n" providerName=vcrobottlschallenge.acme rule="Host(`test.local.com`, `test2.local.com`)" routerName=test_local_com
time="2019-08-27T11:05:25Z" level=error msg="Router defined multiple times with different configurations in [/blissful_montalcini-30429ee0fdcacdc4e96b5924e38cf36a28bb88a3a0bd102d868e3a1ecbef376c /thirsty_herschel-1126613da1c20d4bc83c80dd99007a58136dc62175c0841ecf54766c8f7148d7]" providerName=docker routerName=test_local_com
time="2019-08-27T11:05:32Z" level=error msg="Unable to obtain ACME certificate for domains \"test.local.com,test2.local.com\": unable to generate a certificate for the domains [test.local.com test2.local.com]: acme: Error -> One or more domains had a problem:\n[test.local.com] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for test.local.com, url: \n[test2.local.com] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for test2.local.com, url: \n" routerName=test_local_com rule="Host(`test.local.com`, `test2.local.com`)" providerName=vcrobottlschallenge.acme
time="2019-08-27T11:06:03Z" level=error msg="Unable to obtain ACME certificate for domains \"test.local.com,test2.local.com\": unable to generate a certificate for the domains [test.local.com test2.local.com]: acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rateLimited :: Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/, url: " rule="Host(`test.local.com`, `test2.local.com`)" routerName=test_local_com providerName=vcrobottlschallenge.acme
time="2019-08-27T11:18:21Z" level=error msg="Unable to obtain ACME certificate for domains \"test.local.com,test2.local.com\": unable to generate a certificate for the domains [test.local.com test2.local.com]: acme: Error -> One or more domains had a problem:\n[test.local.com] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for test.local.com, url: \n[test2.local.com] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for test2.local.com, url: \n" providerName=vcrobottlschallenge.acme routerName=test_local_com rule="Host(`test.local.com`, `test2.local.com`)"
time="2019-08-27T11:19:30Z" level=error msg="Unable to obtain ACME certificate for domains \"test.local.com,test2.local.com\": unable to generate a certificate for the domains [test.local.com test2.local.com]: acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rateLimited :: Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/, url: " providerName=vcrobottlschallenge.acme rule="Host(`test.local.com`, `test2.local.com`)" routerName=test_local_com
time="2019-08-27T11:19:34Z" level=error msg="Unable to obtain ACME certificate for domains \"test.local.com,test2.local.com\": unable to generate a certificate for the domains [test.local.com test2.local.com]: acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rateLimited :: Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/, url: " routerName=test_local_com rule="Host(`test.local.com`, `test2.local.com`)" providerName=vcrobottlschallenge.acme
time="2019-08-27T11:20:36Z" level=error msg="Unable to obtain ACME certificate for domains \"test.local.com,test2.local.com\": unable to generate a certificate for the domains [test.local.com test2.local.com]: acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rateLimited :: Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/, url: " providerName=vcrobottlschallenge.acme rule="Host(`test.local.com`, `test2.local.com`)" routerName=test_local_com
time="2019-08-27T11:20:40Z" level=error msg="Unable to obtain ACME certificate for domains \"test.local.com,test2.local.com\": unable to generate a certificate for the domains [test.local.com test2.local.com]: acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rateLimited :: Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/, url: " providerName=vcrobottlschallenge.acme routerName=test_local_com rule="Host(`test.local.com`, `test2.local.com`)"
time="2019-08-27T11:21:20Z" level=error msg="Unable to obtain ACME certificate for domains \"test.local.com,test2.local.com\": unable to generate a certificate for the domains [test.local.com test2.local.com]: acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rateLimited :: Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/, url: " providerName=vcrobottlschallenge.acme routerName=test_local_com rule="Host(`test.local.com`, `test2.local.com`)"
time="2019-08-27T11:26:07Z" level=error msg="Unable to obtain ACME certificate for domains \"test.local.com,test2.local.com\": unable to generate a certificate for the domains [test.local.com test2.local.com]: acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rateLimited :: Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/, url: " providerName=vcrobottlschallenge.acme routerName=test_local_com rule="Host(`test.local.com`, `test2.local.com`)"
time="2019-08-27T11:26:11Z" level=error msg="Unable to obtain ACME certificate for domains \"test.local.com,test2.local.com\": unable to generate a certificate for the domains [test.local.com test2.local.com]: acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rateLimited :: Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/, url: " providerName=vcrobottlschallenge.acme routerName=test_local_com rule="Host(`test.local.com`, `test2.local.com`)"
time="2019-08-27T11:27:56Z" level=error msg="Unable to obtain ACME certificate for domains \"test.local.com,test2.local.com\": unable to generate a certificate for the domains [test.local.com test2.local.com]: acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rateLimited :: Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/, url: " routerName=test_local_com rule="Host(`test.local.com`, `test2.local.com`)" providerName=vcrobottlschallenge.acme
time="2019-08-27T11:28:00Z" level=error msg="Unable to obtain ACME certificate for domains \"test.local.com,test2.local.com\": unable to generate a certificate for the domains [test.local.com test2.local.com]: acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rateLimited :: Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/, url: " routerName=test_local_com rule="Host(`test.local.com`, `test2.local.com`)" providerName=vcrobottlschallenge.acme
time="2019-08-27T11:29:50Z" level=error msg="Unable to obtain ACME certificate for domains \"test.local.com,test2.local.com\": unable to generate a certificate for the domains [test.local.com test2.local.com]: acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rateLimited :: Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/, url: " routerName=test_local_com providerName=vcrobottlschallenge.acme rule="Host(`test.local.com`, `test2.local.com`)"
time="2019-08-27T11:31:19Z" level=error msg="Unable to obtain ACME certificate for domains \"test.local.com,test2.local.com\": unable to generate a certificate for the domains [test.local.com test2.local.com]: acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rateLimited :: Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/, url: " rule="Host(`test.local.com`, `test2.local.com`)" providerName=vcrobottlschallenge.acme routerName=test_local_com
time="2019-08-27T11:31:24Z" level=error msg="Unable to obtain ACME certificate for domains \"test.local.com,test2.local.com\": unable to generate a certificate for the domains [test.local.com test2.local.com]: acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rateLimited :: Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/, url: " providerName=vcrobottlschallenge.acme routerName=test_local_com rule="Host(`test.local.com`, `test2.local.com`)"
time="2019-08-27T11:31:59Z" level=error msg="Unable to obtain ACME certificate for domains \"test.local.com,test2.local.com\": unable to generate a certificate for the domains [test.local.com test2.local.com]: acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rateLimited :: Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/, url: " providerName=vcrobottlschallenge.acme routerName=test_local_com rule="Host(`test.local.com`, `test2.local.com`)"
time="2019-08-27T11:32:03Z" level=error msg="Unable to obtain ACME certificate for domains \"test.local.com,test2.local.com\": unable to generate a certificate for the domains [test.local.com test2.local.com]: acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rateLimited :: Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/, url: " rule="Host(`test.local.com`, `test2.local.com`)" providerName=vcrobottlschallenge.acme routerName=test_local_com
time="2019-08-27T11:32:18Z" level=error msg="Unable to obtain ACME certificate for domains \"test.local.com,test2.local.com\": unable to generate a certificate for the domains [test.local.com test2.local.com]: acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rateLimited :: Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/, url: " providerName=vcrobottlschallenge.acme rule="Host(`test.local.com`, `test2.local.com`)" routerName=test_local_com
time="2019-08-27T11:32:23Z" level=error msg="Unable to obtain ACME certificate for domains \"test.local.com,test2.local.com\": unable to generate a certificate for the domains [test.local.com test2.local.com]: acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rateLimited :: Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/, url: " providerName=vcrobottlschallenge.acme routerName=test_local_com rule="Host(`test.local.com`, `test2.local.com`)"
time="2019-08-27T11:32:33Z" level=error msg="Unable to obtain ACME certificate for domains \"test.local.com,test2.local.com\": unable to generate a certificate for the domains [test.local.com test2.local.com]: acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rateLimited :: Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/, url: " providerName=vcrobottlschallenge.acme routerName=test_local_com rule="Host(`test.local.com`, `test2.local.com`)"
time="2019-08-27T11:32:36Z" level=error msg="Unable to obtain ACME certificate for domains \"test.local.com,test2.local.com\": unable to generate a certificate for the domains [test.local.com test2.local.com]: acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rateLimited :: Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/, url: " providerName=vcrobottlschallenge.acme routerName=test_local_com rule="Host(`test.local.com`, `test2.local.com`)"
time="2019-08-27T11:34:21Z" level=error msg="Unable to obtain ACME certificate for domains \"test.local.com,test2.local.com\": unable to generate a certificate for the domains [test.local.com test2.local.com]: acme: Error -> One or more domains had a problem:\n[test.local.com] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for test.local.com, url: \n[test2.local.com] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for test2.local.com, url: \n" providerName=vcrobottlschallenge.acme routerName=test_local_com rule="Host(`test.local.com`, `test2.local.com`)"
time="2019-08-27T11:34:57Z" level=error msg="Unable to obtain ACME certificate for domains \"test.local.com,test2.local.com\": unable to generate a certificate for the domains [test.local.com test2.local.com]: acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rateLimited :: Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/, url: " routerName=test_local_com rule="Host(`test.local.com`, `test2.local.com`)" providerName=vcrobottlschallenge.acme
time="2019-08-27T11:35:00Z" level=error msg="Unable to obtain ACME certificate for domains \"test.local.com,test2.local.com\": unable to generate a certificate for the domains [test.local.com test2.local.com]: acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rateLimited :: Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/, url: " providerName=vcrobottlschallenge.acme routerName=test_local_com rule="Host(`test.local.com`, `test2.local.com`)"
time="2019-08-27T11:35:12Z" level=error msg="Unable to obtain ACME certificate for domains \"test.local.com,test2.local.com\": unable to generate a certificate for the domains [test.local.com test2.local.com]: acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rateLimited :: Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/, url: " rule="Host(`test.local.com`, `test2.local.com`)" providerName=vcrobottlschallenge.acme routerName=test_local_com
time="2019-08-27T11:35:16Z" level=error msg="Unable to obtain ACME certificate for domains \"test.local.com,test2.local.com\": unable to generate a certificate for the domains [test.local.com test2.local.com]: acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rateLimited :: Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/, url: " routerName=test_local_com rule="Host(`test.local.com`, `test2.local.com`)" providerName=vcrobottlschallenge.acme
time="2019-08-27T11:35:37Z" level=error msg="Unable to obtain ACME certificate for domains \"test.local.com,test2.local.com\": unable to generate a certificate for the domains [test.local.com test2.local.com]: acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rateLimited :: Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/, url: " rule="Host(`test.local.com`, `test2.local.com`)" providerName=vcrobottlschallenge.acme routerName=test_local_com
time="2019-08-27T11:35:40Z" level=error msg="Unable to obtain ACME certificate for domains \"test.local.com,test2.local.com\": unable to generate a certificate for the domains [test.local.com test2.local.com]: acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rateLimited :: Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/, url: " providerName=vcrobottlschallenge.acme routerName=test_local_com rule="Host(`test.local.com`, `test2.local.com`)"
time="2019-08-27T11:35:51Z" level=error msg="Unable to obtain ACME certificate for domains \"test.local.com,test2.local.com\": unable to generate a certificate for the domains [test.local.com test2.local.com]: acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rateLimited :: Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/, url: " routerName=test_local_com providerName=vcrobottlschallenge.acme rule="Host(`test.local.com`, `test2.local.com`)"
time="2019-08-27T11:35:55Z" level=error msg="Unable to obtain ACME certificate for domains \"test.local.com,test2.local.com\": unable to generate a certificate for the domains [test.local.com test2.local.com]: acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rateLimited :: Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/, url: " providerName=vcrobottlschallenge.acme routerName=test_local_com rule="Host(`test.local.com`, `test2.local.com`)"
time="2019-08-27T11:38:48Z" level=error msg="Unable to obtain ACME certificate for domains \"test.local.com,test2.local.com\": unable to generate a certificate for the domains [test.local.com test2.local.com]: acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rateLimited :: Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/, url: " providerName=vcrobottlschallenge.acme routerName=test_local_com rule="Host(`test.local.com`, `test2.local.com`)"
time="2019-08-27T11:38:52Z" level=error msg="Unable to obtain ACME certificate for domains \"test.local.com,test2.local.com\": unable to generate a certificate for the domains [test.local.com test2.local.com]: acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rateLimited :: Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/, url: " rule="Host(`test.local.com`, `test2.local.com`)" providerName=vcrobottlschallenge.acme routerName=test_local_com
time="2019-08-27T11:39:01Z" level=error msg="Unable to obtain ACME certificate for domains \"test.local.com,test2.local.com\": unable to generate a certificate for the domains [test.local.com test2.local.com]: acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rateLimited :: Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/, url: " routerName=test_local_com rule="Host(`test.local.com`, `test2.local.com`)" providerName=vcrobottlschallenge.acme
time="2019-08-27T11:39:35Z" level=error msg="Unable to obtain ACME certificate for domains \"test.local.com,test2.local.com\": unable to generate a certificate for the domains [test.local.com test2.local.com]: acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rateLimited :: Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/, url: " routerName=test_local_com rule="Host(`test.local.com`, `test2.local.com`)" providerName=vcrobottlschallenge.acme
time="2019-08-27T11:39:39Z" level=error msg="Unable to obtain ACME certificate for domains \"test.local.com,test2.local.com\": unable to generate a certificate for the domains [test.local.com test2.local.com]: acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rateLimited :: Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/, url: " providerName=vcrobottlschallenge.acme routerName=test_local_com rule="Host(`test.local.com`, `test2.local.com`)"
time="2019-08-27T11:40:09Z" level=error msg="Unable to obtain ACME certificate for domains \"test.local.com,test2.local.com\": unable to generate a certificate for the domains [test.local.com test2.local.com]: acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rateLimited :: Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/, url: " rule="Host(`test.local.com`, `test2.local.com`)" routerName=test_local_com providerName=vcrobottlschallenge.acme
time="2019-08-27T11:40:12Z" level=error msg="Unable to obtain ACME certificate for domains \"test.local.com,test2.local.com\": unable to generate a certificate for the domains [test.local.com test2.local.com]: acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rateLimited :: Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/, url: " rule="Host(`test.local.com`, `test2.local.com`)" providerName=vcrobottlschallenge.acme routerName=test_local_com
time="2019-08-27T16:26:35Z" level=error msg="\nYou haven't specified the sendAnonymousUsage option, it will be enabled by default.\n"
